<?php
/**
 * ListApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Material list
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\materiallistapi;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * ListApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addListMaterial
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function addListMaterial($list_id, $material_id)
    {
        $this->addListMaterialWithHttpInfo($list_id, $material_id);
    }

    /**
     * Operation addListMaterialWithHttpInfo
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function addListMaterialWithHttpInfo($list_id, $material_id)
    {
        $returnType = '';
        $request = $this->addListMaterialRequest($list_id, $material_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation addListMaterialAsync
     *
     * 
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addListMaterialAsync($list_id, $material_id)
    {
        return $this->addListMaterialAsyncWithHttpInfo($list_id, $material_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addListMaterialAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addListMaterialAsyncWithHttpInfo($list_id, $material_id)
    {
        $returnType = '';
        $request = $this->addListMaterialRequest($list_id, $material_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addListMaterial'
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function addListMaterialRequest($list_id, $material_id)
    {
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling addListMaterial'
            );
        }
        // verify the required parameter 'material_id' is set
        if ($material_id === null || (is_array($material_id) && count($material_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $material_id when calling addListMaterial'
            );
        }

        $resourcePath = '/list/{listId}/{materialId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }
        // path params
        if ($material_id !== null) {
            $resourcePath = str_replace(
                '{' . 'materialId' . '}',
                ObjectSerializer::toPathValue($material_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation checkListMaterial
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function checkListMaterial($list_id, $material_id)
    {
        $this->checkListMaterialWithHttpInfo($list_id, $material_id);
    }

    /**
     * Operation checkListMaterialWithHttpInfo
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function checkListMaterialWithHttpInfo($list_id, $material_id)
    {
        $returnType = '';
        $request = $this->checkListMaterialRequest($list_id, $material_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation checkListMaterialAsync
     *
     * 
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkListMaterialAsync($list_id, $material_id)
    {
        return $this->checkListMaterialAsyncWithHttpInfo($list_id, $material_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation checkListMaterialAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkListMaterialAsyncWithHttpInfo($list_id, $material_id)
    {
        $returnType = '';
        $request = $this->checkListMaterialRequest($list_id, $material_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'checkListMaterial'
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function checkListMaterialRequest($list_id, $material_id)
    {
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling checkListMaterial'
            );
        }
        // verify the required parameter 'material_id' is set
        if ($material_id === null || (is_array($material_id) && count($material_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $material_id when calling checkListMaterial'
            );
        }

        $resourcePath = '/list/{listId}/{materialId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }
        // path params
        if ($material_id !== null) {
            $resourcePath = str_replace(
                '{' . 'materialId' . '}',
                ObjectSerializer::toPathValue($material_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'HEAD',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteListMaterial
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteListMaterial($list_id, $material_id)
    {
        $this->deleteListMaterialWithHttpInfo($list_id, $material_id);
    }

    /**
     * Operation deleteListMaterialWithHttpInfo
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteListMaterialWithHttpInfo($list_id, $material_id)
    {
        $returnType = '';
        $request = $this->deleteListMaterialRequest($list_id, $material_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteListMaterialAsync
     *
     * 
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteListMaterialAsync($list_id, $material_id)
    {
        return $this->deleteListMaterialAsyncWithHttpInfo($list_id, $material_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteListMaterialAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteListMaterialAsyncWithHttpInfo($list_id, $material_id)
    {
        $returnType = '';
        $request = $this->deleteListMaterialRequest($list_id, $material_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteListMaterial'
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId $material_id The identifier of the material. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteListMaterialRequest($list_id, $material_id)
    {
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling deleteListMaterial'
            );
        }
        // verify the required parameter 'material_id' is set
        if ($material_id === null || (is_array($material_id) && count($material_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $material_id when calling deleteListMaterial'
            );
        }

        $resourcePath = '/list/{listId}/{materialId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }
        // path params
        if ($material_id !== null) {
            $resourcePath = str_replace(
                '{' . 'materialId' . '}',
                ObjectSerializer::toPathValue($material_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getList
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId[] $material_ids Filter the list reply down to the given material identifiers. This is the recommended way to check for existence of multiple materials on the list. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\meteriallistclient\ModelList
     */
    public function getList($list_id, $material_ids = null)
    {
        list($response) = $this->getListWithHttpInfo($list_id, $material_ids);
        return $response;
    }

    /**
     * Operation getListWithHttpInfo
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId[] $material_ids Filter the list reply down to the given material identifiers. This is the recommended way to check for existence of multiple materials on the list. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\meteriallistclient\ModelList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getListWithHttpInfo($list_id, $material_ids = null)
    {
        $returnType = '\Swagger\Client\meteriallistclient\ModelList';
        $request = $this->getListRequest($list_id, $material_ids);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\meteriallistclient\ModelList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getListAsync
     *
     * 
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId[] $material_ids Filter the list reply down to the given material identifiers. This is the recommended way to check for existence of multiple materials on the list. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getListAsync($list_id, $material_ids = null)
    {
        return $this->getListAsyncWithHttpInfo($list_id, $material_ids)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getListAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId[] $material_ids Filter the list reply down to the given material identifiers. This is the recommended way to check for existence of multiple materials on the list. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getListAsyncWithHttpInfo($list_id, $material_ids = null)
    {
        $returnType = '\Swagger\Client\meteriallistclient\ModelList';
        $request = $this->getListRequest($list_id, $material_ids);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getList'
     *
     * @param  \Swagger\Client\meteriallistclient\ListId $list_id The identifier of the list to return. Use \&quot;default\&quot; for the default list. (required)
     * @param  \Swagger\Client\meteriallistclient\MaterialId[] $material_ids Filter the list reply down to the given material identifiers. This is the recommended way to check for existence of multiple materials on the list. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getListRequest($list_id, $material_ids = null)
    {
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling getList'
            );
        }

        $resourcePath = '/list/{listId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($material_ids)) {
            $material_ids = ObjectSerializer::serializeCollection($material_ids, 'csv', true);
        }
        if ($material_ids !== null) {
            $queryParams['material_ids'] = ObjectSerializer::toQueryValue($material_ids);
        }

        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
