<?php
define("DING_MATERIALIST_SERVICE_URL","https://prod.materiallist.dandigbib.org");
define("DING_MATERIALIST_TEST_SERVICE_URL","https://test.materiallist.dandigbib.org");
define("DING_MATERIALLIST_MATERIAL_LIST_ID",'default');
/**
 * Implements hook_init().
 *
 * Register autoloader for our (non-Drupal) classes.
 */
use Swagger\Client\materiallistapi\ListApi;

function ding_materiallist_service_init() {
    require_once dirname(__FILE__) . "/SwaggerClient-php/autoload.php";
  }
function ding_materiallist_service_get_list()
{
  module_load_include('inc', 'obb_bib_login', 'obb_bib_login.class');
  if($token = biblogin::isloggedin())
  {
    $client = new ListApi();
    $client->getConfig()->setAccessToken($token->access_token)->setHost(DING_MATERIALIST_TEST_SERVICE_URL);
    $list = $client->getList('default');
    
    return $list->getMaterials();
  }
  else
  {
    return false;
  }

}
function ding_materiallist_service_add_to_list($materialid)
{
  module_load_include('inc', 'obb_bib_login', 'obb_bib_login.class');
  if($token = biblogin::isloggedin())
  {
    $client = new ListApi();
    $client->getConfig()->setAccessToken($token->access_token)->setHost(DING_MATERIALIST_TEST_SERVICE_URL);
    $result = $client->addListMaterial(DING_MATERIALLIST_MATERIAL_LIST_ID,$materialid);
  }
  else
  {
    return false;
  }
}
function ding_materiallist_service_remove_from_list()
{
  module_load_include('inc', 'obb_bib_login', 'obb_bib_login.class');
  if($token = biblogin::isloggedin())
  {
    $client = new ListApi();
    $client->getConfig()->setAccessToken($token->access_token)->setHost(DING_MATERIALIST_TEST_SERVICE_URL);
    $result = $client>deleteListMaterial(DING_MATERIALLIST_MATERIAL_LIST_ID,$materialid);
  }
  else
  {
    return false;
  }
}

function ding_materiallist_service_test()
{
    $data = ding_materiallist_service_get_list();
    
    foreach($data as $material)
    {
      echo $material;
    }
    return;
}
/*
* They do not use the open platform login service directly. 
*/

function biblogin_get_token()
{

}
/**
 * Implements hook_menu().
 */
function ding_materiallist_service_menu() {
     $items['materiallist/test'] = array(
       'title' => 'test',
       'page callback' => 'ding_materiallist_service_test',
       'type' => MENU_CALLBACK,
       'access arguments' => array(
        'access content',
      ),
     );
     return $items;
   }